name: Lint and Unit Tests
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: xdebug
      - name: Install Dependencies
        run: composer install
      - name: Run Tests
        run: ./vendor/bin/phpunit --coverage-html coverage-github
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: rapport-couverture-tp
          path: coverage-github