name: TestCafe CI

on: [push]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installer TestCafe
        run: npm install testcafe

      - name: Exécuter les tests en mode headless
        # On remplace chromium par chrome et on ajoute --no-sandbox
        run: npx testcafe "chrome:headless --no-sandbox" test_cafe.js