name: TestCafe PHP CI

on: [push]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installer TestCafe
        run: npm install testcafe

      - name: Démarrer le serveur PHP et lancer les tests
        run: |
          # On lance le serveur PHP en arrière-plan (&)
          php -S localhost:8000 & 
          # On attend 2 secondes que le serveur soit prêt
          sleep 2
          # On lance TestCafe
          npx testcafe "chrome:headless --no-sandbox" test_cafe.js